# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-11 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autotask_hipchat_test', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauthcredentials',
            name='access_token',
            field=models.CharField(default='none', max_length=255),
        ),
    ]
